version: "3.9"
services:
  server:
    networks:
      - internal
    build:
      context: ./docker
      dockerfile: postgres_server
    ports:
      - "5432:5432"
  pga:
    networks:
      - internal
    build:
      context: ./docker
      dockerfile: postgres_pga
    depends_on:
        - server
    ports:
      - "5433:80"
networks:
  internal: